PaylocityWeb/ViewModels/EmpDetailsViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Models;

namespace PaylocityWeb.ViewModels
{
    public class EmpDetailsViewModel
    {
        public Employee employee { get; set; }

        [Display(Name = "Add dependent")]
        public List<Dependent> dependents { get; set; }

        public decimal PayrollDeduction { get; set; }

        public decimal PayAfterBenefitDeduction { get; set; }
    }
}

PaylocityWeb/Controllers/EmployeeController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using Models;
using Repository;
using Services;
using PaylocityWeb.ViewModels;

namespace PaylocityWeb.Controllers
{
    public class EmployeeController : Controller
    {
        private IEmployeeRepository empRepo;
        private IConfigItemRepository configRepo;

        public EmployeeController()
        {
            // Improvement: Use IOC instead of initialize here
            empRepo = new MockEmployeeRepository();
            configRepo = new MockConfigItemsRepository();
        }
        public EmployeeController(IEmployeeRepository anEmpRepository, IConfigItemRepository aConfigRepository)
        {
            empRepo = anEmpRepository;
            configRepo = aConfigRepository;
        }

        public ActionResult Index()
        {
            List<Employee> employees = empRepo.GetAllEmployees();
            return View(employees);
        }

        /// <summary>
        /// method to create the add employee form
        /// </summary>
        /// <returns>View</returns>
        [HttpGet]
        public ActionResult _AddEmployee()
        {
            EmpDetailsViewModel model = new EmpDetailsViewModel();
            return PartialView(model);
        }

        /// <summary>
        /// Method to add an employee
        /// </summary>
        /// <param name="employee">the employee to add</param>
        /// <returns>View</returns>
        [HttpPost]
        public ActionResult AddEmployee(EmpDetailsViewModel anEmpDetails)
        {
            BenefitDeductionService empCalcs = new BenefitDeductionService(empRepo, configRepo);
            empRepo.AddEmployee(anEmpDetails.employee, anEmpDetails.dependents);

            return Json(new { id = anEmpDetails.employee.EmployeeId });
        }

        /// <summary>
        /// Method to get employees details
        /// </summary>
        /// <param name="employeeId"></param>
        /// <returns>_Details View</returns>
        [HttpGet]
        public ActionResult GetDetails(int anEmployeeId)
        {
            BenefitDeductionService empCalcs = new BenefitDeductionService(empRepo, configRepo);
            EmpDetailsViewModel empDetails = new EmpDetailsViewModel();
            empDetails.employee = empRepo.GetEmployeeById(anEmployeeId);
            empDetails.employee.BenefitCost = empCalcs.CalculateEmpCost(empDetails.employee);
            empDetails.dependents = empRepo.GetDependents(anEmployeeId);
            foreach (var dependent in empDetails.dependents)
            {
                dependent.BenefitCost = empCalcs.CalculateDependentCost(dependent);
            }
            empDetails.PayrollDeduction = empCalcs.CalculateEmpDeductions(empDetails.employee);
            empDetails.PayAfterBenefitDeduction = empCalcs.CalculatePayAfterBenefitDeduction(empDetails.employee);

            return View("_Details", empDetails);
        }
    }
}

PaylocityWeb/Controllers/HomeController.cs
using System.Web.Mvc;

namespace PaylocityWeb.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

PaylocityWeb/Views/Employee/Index.cshtml
@using Models
@model List<Employee>

<div class="col-12">
    <div class="panel">
        <div class="panel-heading">
            <a href="@Url.Action("_AddEmployee", "Employee")" class="btn btn-primary top-60 action-link-modal">
                Add new employee
            </a>
        </div>
        <div class="panel-body">
            @if (Model.Count == 0)
            {
                <h4 class="h4-head">No employees found</h4>
            }
            else
            {
                <table class="table table-striped">
                    <thead>
                        <tr><th>Name</th><th>Last Name</th><th>Benefit Deduction</th></tr>
                    </thead>
                    <tbody>
                        @foreach (var emp in Model)
                        {
                        <tr>
                            <td>@emp.FirstName</td>
                            <td>@emp.LastName</td>
                            <td class="text-center">
                                <a href="@Url.Action("GetDetails", "Employee", new { anEmployeeId = emp.EmployeeId })" >
                                    Details
                                </a>
                            </td>
                        </tr>
                        }
                    </tbody>
                </table>
            }
                
            </div>
    </div>
</div>

<div id="empDetails" title="Employee Details"></div>
<div id="addEmp" title="Add Employee"></div>
<div id="errorMsgDetails" class="hidden"><strong>There was an error retrieving the Employee's details</strong></div>

PaylocityWeb/Views/Employee/_AddEmployee.cshtml
@using PaylocityWeb.ViewModels
@model EmpDetailsViewModel

@Styles.Render("~/Content/css")
@Styles.Render("~/Content/themes/base/css")
<form id="EmpForm">
    <div class="col-md-10">
        <div id="errorMsg" class="hidden"><strong>There was an error adding the employee</strong></div>
        <div>
            <div>
                <div class="row form-group">
                    <div class="col-md-3">
                        <h5><strong>@Html.LabelFor(model => model.employee.FirstName)</strong></h5>
                    </div>
                    <div class="col-md-2 no-wrap red-text">
                        @Html.TextBoxFor(model => model.employee.FirstName)<br />
                        @Html.ValidationMessageFor(model => model.employee.FirstName)
                    </div>
                </div>
                <div class="row form-group">
                    <div class="col-md-3">
                        <h5><strong>@Html.LabelFor(model => model.employee.LastName)</strong></h5>
                    </div>
                    <div class="col-md-2 no-wrap red-text">
                        @Html.TextBoxFor(model => model.employee.LastName)<br />
                        @Html.ValidationMessageFor(model => model.employee.LastName)
                    </div>
                </div>
                <div class="row form-group">
                    <div class="col-md-2">
                        <table cellpadding="3">
                            <tbody id="dependents">
                                <tr><th><i class="fa fa fa-plus fa-lg"  style="color: #ff8f1c"></i></th><th colspan="2"><strong style="color: #ff8f1c">@Html.LabelFor(model => model.dependents)</strong></th></tr>
                                <tr id="rowErrorMsg" class="hidden"><td class="msg" colspan="3">You can't remove the initial row</td></tr>
                                <tr><th></th><th>Name</th><th style="white-space:nowrap;">Dependent Type</th></tr>
                                <tr id="row0" class="dep-row">
                                    <td>
                                        <i class="fa fa-remove fa-lg" style="color: #ff8f1c" ></i>
                                    </td>
                                    <td>
                                        <input type="text" name="dependents[0].Name" class="dep-name" />
                                    </td>
                                    <td>
                                        <select name="dependents[0].Type" class="dep-type">
                                            <option value="Spouse">Spouse</option>
                                            <option value="Child">Child</option>
                                        </select>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="row form-group">
                    <div class="col-md-6 no-wrap">
                        <button class="btn btn-primary no-wrap" id="AddEmpButton">Add Employee</button>
                    </div>
                    <div id="loading" class="col-md-3 no-wrap hidden">
                        <img src="~/Images/loading.gif" />&nbsp;<strong>Adding employee...</strong>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
<script>
    // need this so the remove row function works with dynamically added rows. because it is a document
    // function, when included in the _layout.cshtml, it caused the function to be called twice. I only need
    // it for this partial view.
    $(document).on('click', '.fa-remove', function () {
        Paylocity.empFunctions.removeDependentRow($(this).closest('tr').attr('id'));
    });
</script>
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/jqueryui")
@Scripts.Render("~/bundles/jqueryval")
@Scripts.Render("~/bundles/Paylocity")

PaylocityWeb/Views/Employee/_Details.cshtml
@using PaylocityWeb.ViewModels
@model EmpDetailsViewModel

    <div class="panel-body">
        <div style="font-size: 20px; color: white; text-align: left; margin: 10px 0;">Employee: @Model.employee.FirstName, @Model.employee.LastName</div>

        <br />
        <table cellpadding="3" class="table table-striped">
            <thead>
                <tr>
                    <th>Per Paycheck</th>
                    <th class="border-bottom">Benefit Costs</th>
                    <th>After benefit deduction</th>
                </tr>
            </thead>
            <tr>
                <td class="align-right thin-borders" >@string.Format("{0:C}", Model.employee.Salary)</td>
                <td class="align-right border-bottom thin-borders">@string.Format("{0:C}", Model.PayrollDeduction)</td>
                <td class="align-right thin-borders">@string.Format("{0:C}", Model.PayAfterBenefitDeduction)</td>
            </tr>
        </table>

        <div style="font-size: 20px; color: white; text-align: left; margin: 10px 0;">Dependents</div>

        <table cellpadding="3" class="table table-striped">
            <thead>
                <tr>
                    <th>
                        <strong>Name</strong>
                    </th>
                    <th>
                        <strong>Status</strong>
                    </th>
                    <th>
                        <strong class="no-wrap">Yearly Cost</strong>
                    </th>
                </tr>
            </thead>
            <tr>
                <td class="thin-borders">@Model.employee.FirstName</td>
                <td class="thin-borders">Self</td>
                <td class="thin-borders">@string.Format("{0:C}", Model.employee.BenefitCost)</td>
            </tr>
            @foreach (var dep in Model.dependents)
            {
                <tr>
                    <td class="thin-borders">@dep.Name</td>
                    <td class="thin-borders">@dep.Type</td>
                    <td class="thin-borders">@string.Format("{0:C}", dep.BenefitCost)</td>
                </tr>
            }
        </table>
    </div>

PaylocityWeb/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<article>
    <p>
        Use this area to provide additional information.
    </p>

    <p>
        Use this area to provide additional information.
    </p>

    <p>
        Use this area to provide additional information.
    </p>
</article>

<aside>
    <h3>Aside Title</h3>
    <p>
        Use this area to provide additional information.
    </p>
    <ul>
        <li>@Html.ActionLink("Home", "Index", "Home")</li>
        <li>@Html.ActionLink("About", "About", "Home")</li>
        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
    </ul>
</aside>

PaylocityWeb/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<section class="contact">
    <header>
        <h3>Phone</h3>
    </header>
    <p>
        <span class="label">Main:</span>
        <span>425.555.0100</span>
    </p>
    <p>
        <span class="label">After Hours:</span>
        <span>425.555.0199</span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Email</h3>
    </header>
    <p>
        <span class="label">Support:</span>
        <span><a href="mailto:Support@example.com">Support@example.com</a></span>
    </p>
    <p>
        <span class="label">Marketing:</span>
        <span><a href="mailto:Marketing@example.com">Marketing@example.com</a></span>
    </p>
    <p>
        <span class="label">General:</span>
        <span><a href="mailto:General@example.com">General@example.com</a></span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Address</h3>
    </header>
    <p>
        One Microsoft Way<br />
        Redmond, WA 98052-6399
    </p>
</section>

PaylocityWeb/Views/Home/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-md-12">
        <div class="panel-body">
            <div class="panel-title">Employee Benefit Deduction</div>
            <a href="@Url.Action("Index", "Employee")" class="btn btn-primary">
                Benefit Deduction
            </a>
        </div>
    </div>
</div>